//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memory_Game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        /// <summary>
        /// The score's id (for database storage)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The score itself
        /// </summary>
        public int score1 { get; set; }

        /// <summary>
        /// The user's id who got the score
        /// </summary>
        public int userID { get; set; }

        /// <summary>
        /// The game mode being played when this score was received
        /// </summary>
        public string gameMode { get; set; }

        /// <summary>
        /// The difficulty being played when this score was received
        /// </summary>
        public string difficulty { get; set; }
    
        public virtual User User { get; set; }
    }
}
