//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memory_Game.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Scores = new HashSet<Score>();
        }
    
        /// <summary>
        /// The user's id for database storage and finding their corresponding scores
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The user's display name (will also be their player name)
        /// </summary>
        [Required(ErrorMessage="Please enter a username")]
        public string username { get; set; }

        /// <summary>
        /// The user's password (to do: maybe don't store in plain text?)
        /// 
        /// </summary>
        [Required(ErrorMessage="Please enter a password")]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
    }
}
